name: Auto Update Website Source Code

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  update:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Only run if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update source code
        run: |
          # Your commands to update source code
          echo "Updating source code..."
          # Example: echo "New content" >> index.html

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatic update of website source code" || echo "No changes to commit"

      - name: Push changes
        run: git push
        
